thomaspoignant/go-feature-flag

.sonarcloud.properties

Actually, sonarcloud can see code smell in tests, we want to avoid that.

Ignore test in sonarcloud

---

README.md
variation.go
variation_test.go

When you call variation methods you get the default result only if you have an error.
Resolve #22 
Resolve #21

Variation return default value only if an error appear

---

config.go
feature_flag.go
go.sum
variation.go
variation_test.go

This PR adds support to logs when calling variation methods.
For that, you should configure a logger in `ffclient.Config{}`. If no logger is configured, the module is not logging anything.
The format of the log looks like:
```
[2020-12-18T15:04:42+01:00] user="random-key", flag="unknown-flag", value="false"
```
Resolve #17

Add log when calling variation

---

README.md
config.go
config_test.go

Add **GitHub** as a newly available backend.
It uses the `HttpRetriever` to get the file, but we add a high-level configuration format to make it easy to configure **GitHub** as your backend.
This also supports the usage of GitHub tokens if your file is in a private repository.
Resolve #28

Add Github retriever

---

README.md
feature_flag.go

Move the default PollInterval to 60 seconds.
Resolve #34

Change default PollInterval to 60s

---

README.md
config.go

Not using the default HTTP Client to have the ability to have a timeout.
It is now possible to configure a timeout for HTTP based retriever (HTTP and Github).
Resolve #45

Refactor to not use default http client (without timeout)

---

README.md
config.go
feature_flag.go
internal/retriever/retriever.go
internal/retriever/retriever_file.go
internal/retriever/retriever_file_test.go
internal/retriever/retriever_http.go
internal/retriever/retriever_http_test.go
internal/retriever/retriever_s3.go
internal/retriever/retriever_s3_test.go
variation_test.go

Now you can pass a `context` to the retriever.
The context is passed via the `ffclient.Context` configuration struct.
Change the signature for the retriever to use the context so now every retriever have to take care of the context if possible.

Use context when retrieve the flags

---

README.md
config.go
config_test.go
feature_flag_test.go

⚠️  this PR include breaking changes.
In this PR I change the way to pass the `Retriever` in the config.
We don't have a property for each type of Retriever but only on `Retriever` which can manage all types of Retriever.
The main reason is to have the `aws/aws-sdk-go` as a dependency only if you are using the `S3Retriever`. With this new syntax, we don't force you to have the SDK if you are not using it.
If you were using `HTTPRetriever`, `S3Retriever` or `GithubRetriever`, the change consists only of changing the key in the config.
```go
// Before v0.5.0
err := ffclient.Init(ffclient.Config{
PollInterval: 3,
HTTPRetriever: &ffClient.HTTPRetriever{
URL:    "http://example.com/test.yaml",
},
})
// Since v0.5.0
err := ffclient.Init(ffclient.Config{
PollInterval: 3,
Retriever: …
```

Force to use only one retriever at the time 

---

feature_flag.go
feature_flag_test.go
ffuser/user.go
ffuser/user_builder.go
go.mod
internal/cache/cache.go
internal/cache/cache_test.go
internal/flags/flag.go
internal/flags/flag_test.go
variation.go
variation_test.go

Refactoring of the code to avoid as much as possible the usage of global variables.
Resolve #52

Refactor to avoid global variable as much as possible

---

.golangci.yml
README.md
feature_flag.go
feature_flag_test.go
testdata/test-instance2.yaml
variation.go
variation_test.go

This PR allows you to have multiple `go-feature-flag` instances in the same application.
Nothing changes if you don't need it, you can still use the built-in singleton like provided by the package.
If you need to use files from different places you can create your own instance of `go-feature-flag`:
```go
x, err := ffclient.New(Config{ Retriever: &ffclient.HTTPRetriever{{URL: "http://example.com/test.yaml",}})
defer x.Close()
y, err := ffclient.New(Config{ Retriever: &ffclient.HTTPRetriever{{URL: "http://example.com/test2.yaml",}})
defer y.Close()
user := ffuser.NewUser("user-key")
x.BoolVariation("test-flag", user, false)
y.BoolVariation("test-flag", user, false)
// ...
```
Resolve #56

Allow multiple go-feature-flag

---

background_updater.go
feature_flag.go
feature_flag_test.go
go.mod
go.sum
internal/cache/cache.go
internal/cache/cache_test.go
variation_test.go

Remove dependency to `gocron`, using a ticker to manage background update of the flag.
Configure properly the `RWMutex` to avoid **data races**.
Resolve #57

Remove gocron dependency

---

Makefile
feature_flag.go
feature_flag_test.go
internal/cache/cache.go
internal/cache/cache_test.go
internal/cache/diff_cache.go
internal/cache/flag_cache.go
internal/cache/flag_cache_test.go
internal/cache/notification_service.go
internal/cache/notification_service_test.go
internal/cache/notifier.go
internal/cache/notifier_log.go
internal/cache/notifier_log_test.go

This PR is the first element to implement #16 to be notified when a flag change.
Expect no change on how `go-feature-flag` is working, this only refactors how we log the flag changes and makes it easy to had more system for notifications.
The logs are now used as one type of notifications.
None

Create a notification system when flags changes

---

internal/notifier/notifier_webhook.go

The error was not handled when we had no logger.

Handle error even if the logger is nil

---

feature_flag.go

If you the `ffclient.Init` method return an error and you don't exit at that moment, the `ffclient.Close` function can panic.
Example:
```go
err := ffclient.Init(ffclient.Config{
PollInterval: 3,
Retriever: &ffclient.FileRetriever{
Path: "testdata/flag-config2.toml",
},
FileFormat: "toml",
})
defer ffclient.Close()
```
This PR avoids panic while calling the `Close` method if no cache initialized.

Don't panic when defer a cache that has failed to init

---

README.md
config.go
internal/HTTPClient.go
internal/notifier/notifier_webhook.go
internal/notifier/notifier_webhook_test.go
notifier.go
notifier_test.go
retriever.go

- The config field `Webhooks` used to notify an API when a flag has changed is too restrictive because we need to have other types of service to call when a flag has changed.
This PR introduces a new field called `Notifiers` in place of the `Webhooks` field to be able to have different types of notifiers when a flag has changed _(slack can be a great example)_.
Based on that the field **`Webhooks`** is deprecated and will continue to be supported in the next versions.
It will be removed in a future release. (Check **migration** section bellow to see how to re-configure your webhooks).
- This PR contains also a small change around the `HTTPClient` used at different place to have a central place where we can configure it.
If you were using `Webhooks` before, you should have a configuration …

Deprecate the webhook field to have the field Notifiers instead

---

detectRaces.sh
internal/cache/cache.go

Sometimes when running the tests we detect a race condition in the cache.
Resolve #79

Fix a race condition that can be rarely detected while running tests

---

internal/cache/cache_test.go
internal/model/flag_test.go
internal/retriever/retriever_file_test.go
internal/retriever/retriever_http_test.go
variation_test.go

Some tests were not using `testify`, this PR tries to have the same test strategy everywhere.

Use testify everywhere

---

.golangci.yml
.pre-commit-config.yaml

Bump version of `golangci-lint` to `v1.39.0` for `pre-commit`.

Bump to v1.39.0 version of golangci

---

.circleci/config.yml
Makefile

- CircleCI will use go 1.16
- Change in the `Makefile` to send data to **coveralls** only in the CI.

CI: Upgrade CI to go 1.16 + Scope coveralls

---

README.md
feature_flag.go
feature_flag_test.go
ffexporter/common.go
ffexporter/common_test.go
ffexporter/file.go
ffexporter/file_test.go
ffexporter/log.go
ffexporter/log_test.go
internal/exporter/data_exporter.go
internal/exporter/data_exporter_test.go
testutils/MockExporter.go
variation.go
variation_test.go

Before this PR if we had a logger in the configuration we were logging all variations.
Since it can be a lot of logs we don't want to automatically log like it was before.
This PR removes the automatic logging strategy and replaces it with a **log data exporter**.
⚠️ Breaking changes
If you were using these logs, you need to add the **log data exporter** to your configuration.
```golang
err := Init(Config{
// ...
DataExporter: DataExporter{
Exporter: &ffexporter.Log{},
},
})
```
Resolve #90

Add a log data exporter 

---

README.md
config.go
feature_flag.go
feature_flag_test.go

The default behavior is to return an error if the flag file we want to retrieve is not available.
We don't change this behavior but we add a new configuration param `StartWithRetrieverError` to accept to start the SDK if the retriever failed to get the flags.
If `StartWithRetrieverError` is **true**, the SDK will start even if we did not get any flags from the retriever. It will serve only default values until the retriever returns the flags.  
The init method will not return any error if the flag file is unreachable.  
Default: **false**
Resolve #83

Add an option to start even when retriever is unreachable

---

README.md
config.go
feature_flag_test.go
internal/notifier/notifier_webhook.go
internal/notifier/notifier_webhook_test.go
notifier.go
notifier_test.go

As explaining in #107 this was a bad naming.
With this PR `PayloadURL` is deprecated and `EndpointURL` is used instead.
Resolve #107

Rename PayloadURL -> EndpointURL

---

README.md
examples/experimentation/flags.yaml
examples/experimentation/main.go
internal/model/flag.go
internal/model/flag_pub_test.go
internal/notifier/notifier_slack_test.go
testdata/internal/notifier/slack/should_call_webhook_and_have_valid_results.json
testutils/convert_types.go

To do proper A/B tests we need to be able to run the flag for a specific amount of time.
You can now in the configuration of the flag set a **start date** and an **end date** for your flags.
If you are out of the range, your flag will serve the **default** value.
example:
```yaml
experimentation-flag:
percentage: 50
true: "B"
false: "A"
default: "A"
experimentation:
startDate: 2021-03-20T00:00:00.10-05:00
endDate: 2021-03-21T00:00:00.10-05:00
```
Resolve #102

Add experimentation capability

---

feature_flag.go
ffexporter/file.go
ffexporter/file_test.go
ffexporter/log.go
ffexporter/log_test.go
ffexporter/s3.go
ffexporter/s3_test.go
ffexporter/webhook.go
ffexporter/webhook_test.go
internal/exporter/data_exporter.go
internal/exporter/data_exporter_test.go
testutils/mock_exporter.go
variation_test.go

This PR use the context we pass in the configuration when we call the data exporter.
Resolve #116

Use context when calling the exporter

---

internal/model/flag.go
internal/model/flag_pub_test.go
internal/model/rollout.go
internal/model/rollout_test.go

In version `v0.13.0` we introduced the configuration option `experimentation` for your flags.
The field was introduced at the wrong level because it is supposed to be under `rollout` and it was not.
The `v0.13.1` has fixed the problem but we have continued to support both configurations.
⚠️ This PR removes the support of the old configuration, so check your flag file to be sure that you've configured the good format.
Since the version `v0.13.0` and the associate documentation was here only for a quick period it should be ok, but this worth checking.
Resolve #114

Remove deprecated experimentation field

---

variation.go

`JSONVariation` are notified twice that result in an error in the data export.

JSON Variation are notified twice

---

testdata/ffclient/all_flags/config_flag/flag-config-with-error.yaml
testdata/ffclient/all_flags/marshal_json/error_in_flag_0.json
variation.go
variation_test.go

We had a problem when the **True** value was not correctly set the `AllFlagsState` function was crashing.
This fix avoids the crash and we are using the default value.
Resolve #158

AllFlagsSet Don't crash when flag is not correctly initialized 

---

feature_flag_test.go
variation.go
variation_test.go

There is a problem when exporting the variation type in the `dataExporter`, we had the wrong `VariationType` when we were requesting the wrong type.
The PR fixed the issue and add more tests to prevent that in the future.

(bug) Fix a problem in the exported data for the variation type

---

README.md
docs/flag_format.md

[**GO Feature Flag Editor**](https://thomaspoignant.github.io/go-feature-flag-editor/) is a simple editor to create your flag files.
Resolve #177

Documentation to link go-feature-flag-editor

---

internal/cache/cache.go
internal/cache/flag_cache.go
internal/flag/constant.go
internal/flagv1/flag_data.go
internal/flagv1/flag_pub_test.go
internal/flagv1/variation_type.go
variation.go

Now the variation type is handle by a string and not a enum to prepare for #180.

Variation type in string

---

internal/cache/cache_manager.go

During the build on main an error occurred https://github.com/thomaspoignant/go-feature-flag/runs/3144737037?check_suite_focus=true
This PR tries to fix it.

Test if nil before calling all

---

docs/data_collection/custom.md
feature_flag_test.go
ffexporter/common.go
ffexporter/feature_event.go
ffexporter/file.go
ffexporter/file_test.go
ffexporter/log.go
ffexporter/log_test.go
ffexporter/s3.go
ffexporter/s3_test.go
ffexporter/webhook.go
ffexporter/webhook_test.go
internal/exporter/data_exporter.go
internal/exporter/data_exporter_test.go
testutils/mock/exporter.go
variation.go

It was not possible to implement a custom `Exporter` because `FeatureEvent` was in the internal package.
Now `FeatureEvent` is in the `ffexporter` package so we are able to create custom `Exporter`.
Resolve #224

Expose FeatureEvent publicly

---

README.md
docs/data_collection/google_cloud_storage.md
docs/flag_file/google_cloud_storage.md
examples/data_export_googlecloudstorage/flags.yaml
examples/data_export_googlecloudstorage/main.go
ffexporter/google_cloud_storage.go
ffexporter/google_cloud_storage_test.go
mkdocs.yml

Add a new `Exporter` to export data in Google Cloud Storage.
Resolve #230

Adding the support to google cloud storage as data exporter

---

feature_flag.go
feature_flag_test.go
internal/cache/cache_manager.go
internal/cache/cache_manager_test.go
variation_test.go

Add a new function `GetCacheRefreshDate()` that allows getting the last time the cache was refreshed.
Resolve #238

Add method to get the last time the cache was updated

---

docs/data_collection/log.md
ffexporter/log.go
ffexporter/log_test.go

Deprecate field `Format` and use `LogFormat` instead to avoid confusion in field name with other `exporter`.

Deprecate Format and use LogFormat instead

---

feature_flag.go
feature_flag_test.go
variation.go
variation_test.go

This allows retrieving flag cache metadata like version, rule etc
so the application can use it for visibility purposes. i.e: you want to
know what version of a specific flag your `ffclient` is currently using
resolves #251

Add new GetFlagsFromCache public method

---

docs/configuration.md
docs/flag_format.md
mkdocs.yml

Adding a section in the documentation to explain environments.
Documentation linked to #246

Adding section in the documentation to explain environments

---

go.mod
go.sum

Problem:
Antlr have upgraded with some breaking change which impacts the rule parser used by feature flags and was resolved (https://github.com/nikunjy/rules/pull/24), thus far we could also update dependencies related to it, and also bump go version to 1.17
Resolve #

chore: bump golang, antlr and rule parser version

---

notifier/slacknotifier/notifier.go
notifier/slacknotifier/notifier_test.go

SlackWebhookURL should be a string for compatibility reason

SlackWebhookURL should be a string for compatibility reason

---

exporter/fileexporter/exporter_test.go
exporter/gcstorageexporter/exporter.go
exporter/logsexporter/exporter_test.go
exporter/s3exporter/exporter.go
exporter/s3exporter/exporter_test.go
exporter/webhookexporter/exporter.go
exporter/webhookexporter/exporter_test.go
feature_flag_bench_test.go
feature_flag_test.go
internal/dataexporter/data_exporter_test.go
notifier/logsnotifier/notifier_test.go
notifier/slacknotifier/notifier.go
notifier/slacknotifier/notifier_test.go
notifier/webhooknotifier/notifier.go
notifier/webhooknotifier/notifier_test.go
retriever/fileretriever/retriever.go
retriever/gcstorageretriever/retriever.go
retriever/gcstorageretriever/retriever_test.go
retriever/httpretriever/retriever.go
retriever/s3retriever/retriever.go
retriever/s3retriever/retriever_test.go
testutils/mock/httpmock.go
testutils/mock_gc_storage_reader.go
testutils/mock_httpclient.go
testutils/mock_s3manager.go
variation_test.go

`ioutil` package is deprecated, we are using the new native functions.

Stop using ioutil package

---

README.md

This PR fixes a misspelling of ecosystem, and fixes a grammatical error in README.md

fixed some grammar and spelling in README.md

---

variation.go
variation_test.go

Fix the error when calling variation before initialization.
The SDK was panicking if `ff.BoolVariation` or other variations functions were called before the initialization.
This PR ensure that we are not panicking anymore and that we return the default value.
Resolve #360

Fix error when calling variation before initialisation

---

.goreleaser.yaml

Goreleaser was not able to generate the archive and was failing.
_See https://github.com/thomaspoignant/go-feature-flag/actions/runs/3248914028/jobs/5330696927_.

Fix goreleaser archive fail

---

.github/workflows/release.yml

This new workflow will create a new tag for the documentation everytime we release a new version.
The steps are the following:
-  Create the new version based on the tag name (https://docusaurus.io/docs/versioning#tagging-a-new-version)
-  Merge the change into the main branch
-  When merged to the main branch another GHA will trigger and release the tagged version.
Resolve #390

Create new documentation tag

---

docs/docs/openfeature_sdk/openfeature_dotnet.mdx

Add documentation on how to use the `.NET` SDK.

Doc dotnet

---

feature_flag.go

This is the implementation of the proposed solution on this PR https://github.com/thomaspoignant/go-feature-flag/pull/425.
Resolve #425

Fix race condition when closing not using the singleton

---

examples/data_export_file/flags.yaml
examples/data_export_googlecloudstorage/flags.yaml
examples/data_export_s3/flags.yaml
examples/retriever_configmap/flags.yaml
examples/retriever_file/flags.yaml
examples/retriever_github/flags.yaml
examples/retriever_http/flags.yaml

There is a double quote present in the keys for config files exists in `examples` directory and generating below error:
2023/02/05 21:51:11 something went wrong when getting the flag: wrong variation used for flag new-admin-access
With this change, it will be fixed by removing the double quotes.
Resolve # Not Applicable

Fix config files for examples directory

---

.goreleaser.yaml
Makefile
README.md
cmd/lint/DOCKERHUB.md
cmd/lint/Dockerfile
cmd/lint/README.md
cmd/lint/linter.go
cmd/lint/linter_test.go
cmd/lint/main.go
cmd/lint/testdata/invalid-rule.yaml
cmd/lint/testdata/invalid.json
cmd/lint/testdata/invalid.toml
cmd/lint/testdata/invalid.yaml
cmd/lint/testdata/no-default-rule.yaml
cmd/lint/testdata/no-variation.yaml

This PR adds a new lint command to verify that flag files can be parsed by GO Feature Flag.
The command will exit with a non-zero code if any errors are detected. Individual errors are printed out to stderr.
It's pretty barebones but does the job well. We could consider adding different output formats like json to enable easier processing of the errors, but that would require a little more design consideration.
It's been a while since I wrote any Go, so don't feel like you have to be nice in the comments 😉
Returning `[]error` from `Lint` doesn't feel idiomatic at all. I've considered bringing a dependency like https://github.com/hashicorp/go-multierror but I'd like to get your opinion first.
We could also create a struct to store errors and return that instead. Something like:
```go
type …
```

Add lint command

---

variation.go
variation_test.go

ff.RawVariation not working with default value as nil.
This PR allow to have nil as default value.
Resolve #525

Fix 525: ff.RawVariation not working with default value as nil

---

website/docs/linter.md

Thank you for adding the `lint` documentation! I was waiting to add it to our repository to write it, but you had already done it.
I think it might be useful to show people how to use it in GitHub actions, so here it is.

Add GitHub action documentation (lint)

---

Makefile
cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
cmd/relayproxy/helm-charts/relay-proxy/README.md
cmd/relayproxy/helm-charts/relay-proxy/README.md.gotmpl
cmd/relayproxy/helm-charts/relay-proxy/values.yaml

Why: to generate helm docs based on values.yaml file
How:
- using helm-docs[1] binary
- adding readme.go.tmpl as a template to generate docs
Tags: #helm-docs #makefile #readme #issue-664
A new command has been added as a part of Makefile to generate the helm documentation.
Resolve #664 
[1] https://github.com/norwoodj/helm-docs

Adds generate-helm-docs to makefile

---

cmd/relayproxy/config/config.go
cmd/relayproxy/config/exporter.go
cmd/relayproxy/config/exporter_test.go
cmd/relayproxy/main.go
cmd/relayproxy/service/gofeatureflag.go
cmd/relayproxy/service/gofeatureflag_test.go

fix not able to customize `parquetCompressionCodec` in relay-proxy
Resolve #157

fix relay proxy config - support parquet for data collection

---

cmd/relayproxy/config/config.go

Add missing default extension for configuration

fix: Add missing default extension for configuration

---

.github/workflows/release-helm.yml
.github/workflows/release.yml

Since we are not using any GH Token to open the PR, the CI is not triggering.
This add a new param to use the GH Token while opening the PRs.

Using GH token to trigger CI

---

config_collector.go
exporter/data_exporter.go
exporter/data_exporter_test.go
exporter/exporter.go
feature_flag.go
variation_test.go

Move everything related to data exporter in the same folder

Move everything related to data exporter in the same folder

---

cmd/relayproxy/controller/collect_eval_data.go
cmd/relayproxy/controller/collect_eval_data_test.go
cmd/relayproxy/model/collect_eval_data_request.go
cmd/relayproxy/testdata/controller/collect_eval_data/invalid_request.json
cmd/relayproxy/testdata/controller/collect_eval_data/invalid_request_data_null.json
cmd/relayproxy/testdata/controller/collect_eval_data/valid_request.json

This PR change endpoint input to be compatible with the webhook exporter.
⚠️ This is a breaking change, but since this is a recent addition and it is not documented yet, we accept to have a braking change for this endpoint.

Change endpoint input to be compatible with the webhook exporter

---

cmd/relayproxy/config/config.go
exporter/data_exporter_test.go
website/docs/openfeature_sdk/openfeature_go.mdx

The go template configuration for the exporter is broken.
This PR fix the format.

fix: CSV export format is broken

---

cmd/relayproxy/config/retriever.go
cmd/relayproxy/service/gofeatureflag.go
cmd/relayproxy/service/gofeatureflag_test.go
website/docs/relay_proxy/configure_relay_proxy.md

Deprecate the field `GithubToken` in the relay proxy configuration to use a more generic field called `token`.
Resolve #752

Deprecate GithubToken field in favor of token

---

internal/flag/rule.go

Trim query because rules are working better as a oneliner

Trim query because rules are working better as a oneliner

---

cmd/relayproxy/api/server.go

The default is set in the configuration so we never use this 3000 value, but it is misleading.

Change wrong default port

---

.github/workflows/release.yml
.goreleaser.yaml
cmd/relayproxy/DOCKERHUB_deprecated.md
cmd/relayproxy/DockerfileGoreleaser
cmd/relayproxy/DockerfileGoreleaserRelayProxy

Release relay proxy under 2 names.
As discussed [here](https://github.com/thomaspoignant/go-feature-flag/issues/753) the name `relay proxy` is a bit misleading, so to prepare any change we will release the relay proxy with 2 versions 
- `go-feature-flag-relay-proxy` 
- `go-feature-flag`
It will ease the change of name in the future.

Release relay proxy under 2 names

---

README.md
website/docs/go_module/store_file/gitlab.md
website/versioned_docs/version-v1.10.0/go_module/store_file/gitlab.md
website/versioned_docs/version-v1.10.1/go_module/store_file/gitlab.md
website/versioned_docs/version-v1.10.2/go_module/store_file/gitlab.md
website/versioned_docs/version-v1.10.3/go_module/store_file/gitlab.md
website/versioned_docs/version-v1.10.4/go_module/store_file/gitlab.md
website/versioned_docs/version-v1.11.0/go_module/store_file/gitlab.md

This documentation pages for the GitLab retriever stated GitHub.

docs: fix GitLab title pages

---

retriever/githubretriever/retriever.go
retriever/githubretriever/retriever_test.go
testutils/mock/http_mock.go

Before this PR we were using the GitHub public link to retrieve your feature flags.
It was closing some caching issues.
This PR now uses the API directly so it should avoid this issues.

fix: Use GITHUB api instead of the public link

---

cmd/relayproxy/service/notifier_relayproxy.go
cmd/relayproxy/service/notifier_relayproxy_test.go
internal/cache/notification_service.go
notifier/logsnotifier/notifier.go
notifier/logsnotifier/notifier_test.go
notifier/notifier.go
notifier/slacknotifier/notifier.go
notifier/slacknotifier/notifier_test.go
notifier/webhooknotifier/notifier.go
notifier/webhooknotifier/notifier_test.go
website/docs/go_module/notifier/custom.md

⚠️⚠️⚠️ This is a breaking change if you had custom notifiers, you will have to update them before using this version.
The previous interface for the `Notifier` was:
```go
func (n *notifierRelayProxy) Notify(diff notifier.DiffCache, waitGroup *sync.WaitGroup) error
```
As you can see we were requesting people implementing custom notifiers to take care of the `sync.WaitGroup` lifecycle.
It could be a source of bugs if the notifiers were not doing it properly.
We changed the interface to
```go
func (n *notifierRelayProxy) Notify(diff notifier.DiffCache) error
```
and now the lifecycle of the go routine is purely managed by GO Feature Flag.

⚠️ Changing the Notifier interface to simplify go routine handling

---

openfeature/provider_tests/integration_tests.sh

We have an issue because of a bug in the java SDK, we have to deactivate the test.
Please follow this issue https://github.com/open-feature/java-sdk/issues/552 when resolved we can reactivate the tests.

Deactivate java integration test

---

cmd/relayproxy/service/gofeatureflag.go
cmd/relayproxy/service/gofeatureflag_test.go
retriever/s3retriever/retriever.go
retriever/s3retrieverv2/downloader_api.go
retriever/s3retrieverv2/retriever.go
retriever/s3retrieverv2/retriever_test.go
retriever/s3retrieverv2/testdata/flag-config.yaml
testutils/s3managerv2_mock.go
website/docs/go_module/store_file/s3.md
website/docs/openfeature_sdk/server_providers/openfeature_javascript.mdx

New exporter for s3 that supports go-aws-sdk-v2 SDK.
To avoid breaking actual integrations we are introducing a `v2` for the exporter, to use it please use `s3retrieverv2.Retriever` rather than `s3retriever.Retriever`.
We have also deprecated the `s3retriever.Retriever` and updated the documentation to recommend using `v2`.
Resolve #987

New retriever for s3 that supports go-aws-sdk-v2 SDK

---

.github/workflows/ci.yml
.github/workflows/release.yml
go.mod
go.sum

We cannot bump to v1.5.0 because it requires go 1.21 and our current compact is 1.19.

Bump nikunjy/rules to v1.4.0

---

cmd/relayproxy/config/retriever.go

In the struct tag declaration of RetrieverConf's Object field, which is being mistaken for `bucket`, the correct value should be `object`.
Resolve #1265

Fix confusion in RetrieverConf's struct tag declaration

---

cmd/editor/main.go
cmd/relayproxy/controller/utils.go
cmd/relayproxy/controller/utils_test.go
ffcontext/context_builder.go
go.mod
internal/utils/evaluation_ctx_converter.go
internal/utils/evaluation_ctx_converter_test.go
internal/utils/number_utils.go
internal/utils/number_utils_test.go

When converting the evaluation context int fields where seen as float, which result to some errors when building rules.
Resolve #1338

fix(relay-proxy): When converting the context int where seen as float

---

cmd/relayproxy/helm-charts/relay-proxy/templates/hpa.yaml

`autoscaling/v2beta1` is deprecated in K8s v1.25 and should be replaced with `autoscaling/v2` since K8s v1.23. This change adds Helm conditional to check whether K8s API supports newer version and use it in the rendered template if possible.

[BUGFIX] Helm conditional for HPA K8s API version

---

.github/workflows/repostats-collector.yml

I was getting daily reports of a failed GH action run on the fork.
Turned out to be the repo status report workflow, so I added a check to make sure it should run
Resolve #

chore: only run status report for root repo

---

cmd/editor/main.go
cmd/relayproxy/testdata/controller/flag_eval/rule_apply_false_response.json
cmd/relayproxy/testdata/controller/flag_eval/rule_apply_response.json
variation.go
variation_test.go
website/docs/configure_flag/rule_format.md

The Evaluated Rule Name is needed during our experiment analysis phase. During this phase, we need to keep track of the user that has been assigned to a defined variant. Our experiment tends to have different rules, such as internal experiments, free account experiments, etc... Those phases can happen in parallel, and we need to define how the phase is performing. That way the $reason$ on the response is not enough and the metadata must be enhanced. 
Because it is possible to set a variant to a target group, if we don't keep track of the rule, we can have a Sample Mismatch. E.g. if we set enterprise user to variant off, and not enterprise user to 50:50 on and off. That means we will have many more off-users than on. In this case, the reason is enough, but we have the case where enterprise …

(feature) Passing the Evaluated Rule Name to the Metadata

---

cmd/relayproxy/api/server.go
cmd/relayproxy/api/server_test.go
cmd/relayproxy/config/config.go
website/docs/relay_proxy/monitor_relay_proxy.md

Following issue #1499, this PR introduces the possibility of running `metrics` and `health checks` on different ports.
This is a requirement for some companies that prefer not to mix the 2 things simultaneously.
In this implementation, we are starting another instance of `echo` for the metrics if the param `monitoringPort` is set in the configuration.
If this option is not set the monitoring will continue to work on the same port of the business logic.
Resolve #1499

relayproxy: Add the possibility to have 2 differents port for metrics and business

---

variation_test.go

Increase waiting time in test

---

.golangci.yml
Makefile

Latest golangci update is breaking the CI.
This PR change the deprecation command line params.

Fix: update the config of golangci-lint

---

variation.go
variation_test.go

fix panic concurrent map writes when constructing metadata

---

retriever/s3retrieverv2/retriever.go

Update S3 retriever.go mechanism 

---

retriever/s3retrieverv2/retriever.go
retriever/s3retrieverv2/retriever_test.go

Fixes issue with s3Retrieverv2 initialization by checking again for presence of AwsConfig and using that instead of default AWS Config. 
Resolve #1691

Fix: check for s.AwsConfig when initializing s3Retrieverv2

---

cmd/relayproxy/controller/all_flags.go
cmd/relayproxy/controller/collect_eval_data.go
cmd/relayproxy/controller/flag_eval.go
cmd/relayproxy/controller/health.go
cmd/relayproxy/controller/info.go
cmd/relayproxy/controller/ws_flag_change.go
cmd/relayproxy/docs/docs.go
cmd/relayproxy/docs/swagger.json
cmd/relayproxy/docs/swagger.yaml
cmd/relayproxy/model/ofrep_error_response.go
cmd/relayproxy/model/ofrep_success_response.go
cmd/relayproxy/modeldocs/metricsController.go
cmd/relayproxy/ofrep/evaluate.go
cmd/relayproxy/ofrep/evaluate_test.go
cmd/relayproxy/ofrep/ofrepEvaluateError.go
cmd/relayproxy/testdata/ofrep/invalid_context.json
cmd/relayproxy/testdata/ofrep/no_targeting_key_context.json
cmd/relayproxy/testdata/ofrep/responses/invalid_context.json
cmd/relayproxy/testdata/ofrep/responses/invalid_context_with_key.json
cmd/relayproxy/testdata/ofrep/responses/nil_context.json
cmd/relayproxy/testdata/ofrep/responses/nil_context_with_key.json
cmd/relayproxy/testdata/ofrep/responses/no_targeting_key_context.json
cmd/relayproxy/testdata/ofrep/responses/no_targeting_key_context_with_key.json
cmd/relayproxy/testdata/ofrep/responses/not_found.json
cmd/relayproxy/testdata/ofrep/responses/valid_evaluation.json
cmd/relayproxy/testdata/ofrep/responses/valid_response.json
cmd/relayproxy/testdata/ofrep/valid_request.json

OFREP: Add missing flagKey in error responses + adding tests
Resolve #1759 
Resolve #1638

OFREP: Add missing flagKey in error responses + adding tests

---

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml

Automated pull request to bump relay-proxy helm chart version v1.26.0

Bump relay-proxy helm chart version v1.26.0

---

cmd/relayproxy/helm-charts/relay-proxy/values.yaml

This PR fixes an error of type and description in the helm doc generated.
Thanks @tomflenner for raising it in #1820.
Resolve #1823

fix: Helm documentation type error

---

ADOPTERS.md

This PR includes a tiny change just to include [Agentero](https://agentero.com/) in the list of adopters.

chore: update adopters readme with new company

---

cmd/relayproxy/helm-charts/relay-proxy/templates/configmap.yaml
cmd/relayproxy/helm-charts/relay-proxy/values.yaml

Add support for helm [tpl function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) inside the [relayproxy.config](https://github.com/thomaspoignant/go-feature-flag/blob/main/cmd/relayproxy/helm-charts/relay-proxy/values.yaml#L3) helm chart value.
Using the helm cli `helm template goff-1851 . -n goff-1851-namespace` to render the helm chart with these values :
```
relayproxy:
config: | # This is a configuration example for the relay-proxy
listen: 1031
pollingInterval: 1000
startWithRetrieverError: false
test: {{ .Release.Namespace }}
retriever:
kind: http
url: https://raw.githubusercontent.com/thomaspoignant/go-feature-flag/main/examples/retriever_file/flags.goff.yaml
exporter:
kind: log
```
Initially we had this output :
```
---
apiVersion: v1
kind: ConfigMap …
```

chore: Change/1851 helm config templating

---

cmd/relayproxy/ofrep/evaluate.go
cmd/relayproxy/ofrep/evaluate_test.go
cmd/relayproxy/testdata/controller/all_flags/valid_response.json
cmd/relayproxy/testdata/controller/config_flags.yaml
cmd/relayproxy/testdata/ofrep/responses/valid_response.json
cmd/relayproxy/testdata/ofrep/responses/valid_targeting_key_query_response.json
cmd/relayproxy/testdata/ofrep/valid_targeting_key_query_request.json

When calling the evaluation for OFREP we had an issue writing rules using `targetingKey` as key because it was removed from the evaluation context (in favor of `key`).
In this PR we stop removing `targetingKey` to be able to use both key names.
Resolve #1898

fix(OFREP): keep targetingKey in the custom data to continue to have rules enabled

---

exporter/gcstorageexporter/exporter.go

fix: close files in google storage exporter

---

cmd/lint/Dockerfile
cmd/migrationcli/Dockerfile
cmd/relayproxy/DockerfileGoreleaser
cmd/relayproxy/DockerfileGoreleaserRelayProxy

This PR is bumping the base distroless docker image to Debian-12 for all the docker image we publish.
Resolve #1909

feat(docker): Bump base distroless image

---

website/docs/configure_flag/rule_format.md

This PR adds to the documentation what is the evaluation context and why it is important.
Resolve #1904

doc: Add explanation for evaluation context

---

retriever/githubretriever/retriever.go
retriever/githubretriever/retriever_test.go
retriever/httpretriever/retriever.go
retriever/shared/http.go
testutils/mock/http_mock.go

Following the discussion in #1334, this PR logs all the GitHub headers in the error response to understand better if some rate-limiting errors can be the source of the issue.
Resolve #1917

feat(relay-proxy): Add log when Github API in error

---

cmd/relayproxy/config/config.go
cmd/relayproxy/config/config_test.go
cmd/relayproxy/testdata/config/validate-array-env-file.yaml

Resolve [1841](https://github.com/thomaspoignant/go-feature-flag/issues/1841)

fix(relay-proxy): Allow overide of array configuration by environment variables

---

cmd/relayproxy/api/middleware/version.go
cmd/relayproxy/api/middleware/version_test.go
cmd/relayproxy/api/routes_monitoring.go
cmd/relayproxy/api/server.go

Add a new header called `X-GOFEATUREFLAG-VERSION` that display the version of GO Feature Flag in the API responses.

feat(relayproxy): Add middleware to add version in response headers

---

website/versioned_docs/version-v1.29.0/getting_started/using-openfeature.md

Corrected name of image in dockerhub
Resolve #

fix: Update using-openfeature.md - Corrected name of image in dockerhub

---

website/docs/getting_started/using-openfeature.md
website/versioned_docs/version-v1.27.0/getting_started/using-openfeature.md
website/versioned_docs/version-v1.28.0/getting_started/using-openfeature.md
website/versioned_docs/version-v1.28.1/getting_started/using-openfeature.md
website/versioned_docs/version-v1.28.2/getting_started/using-openfeature.md
website/versioned_docs/version-v1.30.0/getting_started/using-openfeature.md

I noticed that the [Getting Started](https://gofeatureflag.org/docs/getting_started/using-openfeature#install-the-relay-proxy) documentation was pointing to a non-existent Docker Hub image, so I corrected it.

docs(website): update relay proxy image name

---

cmd/relayproxy/service/gofeatureflag.go
cmd/relayproxy/service/gofeatureflag_test.go
config_collector.go
exporter/data_exporter.go
exporter/exporter.go
exporter/fileexporter/exporter.go
exporter/fileexporter/exporter_test.go
exporter/gcstorageexporter/exporter.go
exporter/gcstorageexporter/exporter_test.go
exporter/kafkaexporter/exporter.go
exporter/kafkaexporter/exporter_test.go
exporter/logsexporter/exporter.go
exporter/logsexporter/exporter_test.go
exporter/package_info.go
exporter/pubsubexporter/exporter.go
exporter/pubsubexporter/exporter_test.go
exporter/s3exporter/exporter.go
exporter/s3exporter/exporter_test.go
exporter/s3exporterv2/exporter.go
exporter/s3exporterv2/exporter_test.go
exporter/sqsexporter/exporter.go
exporter/sqsexporter/exporter_test.go
exporter/webhookexporter/exporter.go
exporter/webhookexporter/exporter_test.go
testutils/slogutil/message_only_handler.go
website/docs/go_module/data_collection/custom.md

The changes in the log have broken the log exporter by setting the log level to `ERROR` rather than `INFO`.
On this PR we have introduce a new exporter interface to use the new logger so we will be able to set the level of the logs (and back to `INFO` for the exporter).
Resolve #2053

fix: Use fflog for Exporters

---

openfeature/providers/python-provider/tests/mock_responses/bool_targeting_match_no_error_field.json
openfeature/providers/python-provider/tests/test_gofeatureflag_python_provider.py

- Python provider add test without errorCode in response
This is in order to validate this PR #2035

chore(python-provider): add test without errorCode in response

---

go.mod
website/.ci/go.mod

There is a major CVE-2024-24790 in go stdlib, bumping GO will solve it.

fix: Bump to go1.22.5

---

internal/flag/internal_flag.go
internal/flag/internal_flag_test.go

Scheduled steps are included if we have the exact same date (only after).
This PR accept the steps if it is the exact date.
Link to this comment: https://github.com/thomaspoignant/go-feature-flag/issues/2054#issuecomment-2246655478

fix: scheduled steps on exact time

---

cmd/relayproxy/ofrep/evaluate.go
cmd/relayproxy/testdata/ofrep/responses/valid_evaluation.json
cmd/relayproxy/testdata/ofrep/responses/valid_targeting_key_query_response.json

Add cacheable metadata in OFREP API response.

feat(OFREP): Add cacheable metadata

---

ADOPTERS.md

Adding HelloWorldCS to the adopters list

feat: add HelloWorldCS to adopters list

---

.goreleaser.yaml

Address the goreleaser deprecation https://goreleaser.com/deprecations/#snapshotname_template

chore(goreleaser): deprecation snapshot.name_template

---

feature_flag.go

This PR fixes unused format verbs in error messages.
I noticed that there is unused `%v` in the message while GitHub is down.
This should be occurred after 306b11751.
```
{"level":"error","ts":1723678691.5177238,"msg":"error while updating the cache: %v\n","error":{"error":"request to...
```
There is no reported issues.

fix: remove unused format verbs in error messages

---

website/docs/getting_started/using-openfeature.md
website/versioned_docs/version-v1.32.0/getting_started/using-openfeature.md
website/versioned_docs/version-v1.33.0/getting_started/using-openfeature.md

This PR fixes a minor error in the markdown of the "Using Open Feature SDKs" pages.

docs(website): fix invalid markdown

---

.golangci.yml
cmd/relayproxy/api/server.go
cmd/relayproxy/service/gofeatureflag.go

CI was breaking the build because of the deprecation notice due to lack of maintenance of `otelecho`.
For now, we've decided to ignore the notice.
Resolve #2289

chore(CI): Ignore deprecated notice because unmaintained otelecho

---

.goreleaser.yaml

This PR adds pre-defined labels of the OCI Image Specification to the Docker images.
Also updates the homepage URLs of the Homebrew formulae.
Resolve #2249.

feat: add docker labels of the OCI Image Format Specification

---

internal/flag/internal_flag.go
internal/flag/internal_flag_test.go

As reported in issue #2256, in some cases we can have a data race when using a scheduled rollout.
This PR fixes the issue by creating a deep copy of the flag before applying the scheduled steps.
Resolve #2256

fix: Scheduled rollout cause a data race

---

cmd/relayproxy/config/config.go
cmd/relayproxy/config/config_test.go
website/docs/relay_proxy/configure_relay_proxy.md

allow to override authorized keys with env variables

fix: allow to override authorized keys with env variables

---

cmd/migrationcli/converter/converter.go
model/dto/convert_v1.go

Was pulling my hair trying to figure out why the new bucketing didn't work on the server. Turns out we forgot to add it to the converters, so it gets lost in the cache initialization phase.
Tests don't cover this, should they?

fix: add BucketingKey to DTO converter functions

---

openfeature/provider_tests/java-integration-tests/src/test/java/org/gofeatureflag/integrationtests/ProviderTests.java

In the java integration tests we are now using `setProviderAndWait` instead of our custom waiting mechanism.

chore(java): Use setProviderAndWait in the integration tests

---

.goreleaser.yaml
website/docs/relay_proxy/deploy_relay_proxy.md

When releasing GO Feature Flag we will now build and put as an archive a ready-to-be-used AWS lambda binary.
**Why is ready for AWS Lambda?**
- The archive is a zip.
- The binary name inside the zip is `bootstrap`.
- It has been build as `linux arm64` target.
Resolve #2405

feat(release): Add an AWS Lambda ready archive in the releases

---

examples/demo/demo-flags.goff.yaml

fix: convert example flag file to v1

fix: convert example flag file to v1

---

gofferror/empty_bucketing_key.go
internal/flag/internal_flag.go
internal/flag/internal_flag_test.go
internal/flagstate/flag_state.go
internal/flagstate/flag_state_test.go

When not setting a `targetingKey` and calling `allFlagState` we had an error saying that the `TYPE_MISMATCH` which was not explicit enough to understand the issue.
Not we are returning `TARGETING_KEY_MISSING` which is more explicit.
Resolve #2453

fix: Handle errors in flagState conversion

---

website/docs/configure_flag/rollout/progressive.mdx
website/versioned_docs/version-v1.35.0/configure_flag/rollout/progressive.mdx

Update the example used and add a description of how the configuration works. (updated)
Resolve https://github.com/thomaspoignant/go-feature-flag/issues/2452

docs: update progressive rollout docs

---

cmd/relayproxy/api/server.go

In https://github.com/thomaspoignant/go-feature-flag/pull/1503, the code that used to call `s.otelService.Init` was accidentally removed. This restores that code.
Here's proof of spans once again being sent to a local Alloy/Tempo setup:
Note that I _have not_ written a unit test to cover this, as it's quite difficult to do so with how the OTel SDK is configured currently.
I have some ideas on how tracing support can be made more flexible (through use of `autoexport` primarily, and some other changes). I'll issue a PR for that some other time.
Fixes #2479

fix(tracing): Restore OTel tracing support

---

cmd/server

Remove `cmd/server` symlink that is un-used.
> [!NOTE]  
> At some point we wanted to get rid of the name relay-proxy and rather call it go-feature-flag server.
> But now the name is well adopted now, so I think it is ok to remove the symlink.
Resolve #2484

chore: remove unused symlink

---

Makefile
feature_flag_bench_test.go

Scope the benchmark test behind a tag to avoid `init` method to be called all the time.

chore: scope test bench

---

internal/flag/internal_flag.go
internal/flag/internal_flag_test.go
internal/flag/rule.go
variation_all_flags_test.go

In this PR we had a new check when validating a feature flag to check if we reference an undefined variation in one of the rule configuration.
The effect of this PR is double, it will allow the linter to detect those issues and it will discard this flag (and log an error)  for misconfigured flags.
Resolve #2652

feat: Detect undefined variations

---

go.mod
go.sum
notifier/slacknotifier/notifier.go

replace `gdexlab/go-render` by `luci/go-render`.

chore: replace gdexlab/go-render by luci/go-render

---

feature_flag.go

This is a bug fix for #2534 
#2534 had an incorrect logic of NOT calling notifier when the status is not set to `isInit` (=upon polling).
It should:
* NOT call notifier only if `isInit`  && `DisableNotifierOnInit` are BOTH true
* call the notifier in any other cases

fix: Notifier should fire during runtime (if isInit is false)

---

ADOPTERS.md

Updates link to Minder, which has been donated to the OpenSSF.  Stacklok is also using Go Feature Flag internally, and may be using the relay soon.

Add Minder OpenSSF project to adopters

---

internal/utils/hash.go

linter issue with redifinition of max

fix(lint): linter issue with redifinition of max

---

openfeature/providers/python-provider/gofeatureflag_python_provider/data_collector_hook.py
openfeature/providers/python-provider/gofeatureflag_python_provider/options.py
openfeature/providers/python-provider/gofeatureflag_python_provider/provider.py
openfeature/providers/python-provider/tests/docker-compose.yml
openfeature/providers/python-provider/tests/test_gofeatureflag_python_provider.py
openfeature/providers/python-provider/tests/test_websocket_cache_invalidation.py

This PR fixes 2 things:
- Allow to set authorized key in the option if you use an authenticated version of GO Feature Flag
- Fix URL formatting when GOFF is not on the root level of the path.
Resolve #2690 #2671

fix(python): Fix URL formatting + authorized key

---

cmd/relayproxy/docs/docs.go
cmd/relayproxy/docs/swagger.json
cmd/relayproxy/docs/swagger.yaml
cmd/relayproxy/model/user_request.go

`user` field was here for legacy compatibility, but keeping it in the documentation is misleading.
In this PR we remove `user` from swagger doc.

docs(swagger): remove user field in the context

---

openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/main/java/org/gofeatureflag/openfeature/hook/DataCollectorHook.kt
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/test/java/org/gofeatureflag/openfeature/controller/GoFeatureFlagApiTest.kt
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/test/resources/org/gofeatureflag/openfeature/hook/valid_result.json

Currently dataCollector pass events in ms, and it suppose to be in seconds. Now I changed the way it constructed so it would be in seconds.

fix: DataCollectorHook event time converted to seconds

---

cmd/relayproxy/api/server.go

When trying to fix #2758 we have introduced an issue that makes swagger not working anymore.
Resolve #2758

fix(timeout): Fix the swagger issue introduce after fixing #2758

---

cmd/relayproxy/testdata/controller/config_flags.yaml
cmd/relayproxy/testdata/controller/flag_change/flag_change_with_config_change.json
cmd/relayproxy/testdata/controller/flag_change/flag_change_without_config_change.json
internal/flag/internal_flag_test.go
internal/flag/rule.go

Basic rule query check validation for the linter and to validate the flags.
#2786

feat: Test if rule format is valid

---

openfeature/providers/kotlin-provider/README.md
openfeature/providers/kotlin-provider/build.gradle.kts
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/build.gradle.kts
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/main/java/org/gofeatureflag/openfeature/ofrep/OfrepProvider.kt
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/main/java/org/gofeatureflag/openfeature/ofrep/bean/OfrepApiResponse.kt
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/test/java/org/gofeatureflag/openfeature/ofrep/OfrepProviderTest.kt
openfeature/providers/kotlin-provider/gofeatureflag-kotlin-provider/src/test/java/org/gofeatureflag/openfeature/ofrep/controller/OfrepApiTest.kt
website/docs/openfeature_sdk/client_providers/openfeature_android.mdx

In this PR we add support of the flag metadata in the `kotlin` provider.

feat(kotlin-provider): Support flag metadata

---

README.md
website/docs/sdk/server_providers/openfeature_go.mdx
website/docusaurus.config.js
website/src/components/home/HomeHeader/index.js
website/src/components/home/features/index.js

- Change the top buttons on the home page
- Remove duplicate redirection

docs: Change buttons + remove duplicate redirection

---

openfeature/providers/python-provider/gofeatureflag_python_provider/data_collector_hook.py
openfeature/providers/python-provider/gofeatureflag_python_provider/options.py
openfeature/providers/python-provider/gofeatureflag_python_provider/request_data_collector.py
openfeature/providers/python-provider/poetry.lock
openfeature/providers/python-provider/tests/test_gofeatureflag_python_provider.py

Support exporter metadata in python provider.

feat: support exporter metadata in python provider

---

website/versioned_docs/version-v1.41.0/relay-proxy/getting_started.md

typo fix
- typo
- spelling fixed
- verify in the readme

docs: Update getting_started.md

---

cmd/relayproxy/api/opentelemetry/otel.go

As reported by @ybasket, there is an issue in propagating the traces across different services.
This PR configure the propagation for Otel in order to follow the traces across multiple span.
Resolve #3042

fix: OpenTelemetry trace propagation

---

cmd/relayproxy/api/middleware/version.go
cmd/relayproxy/api/middleware/version_test.go
cmd/relayproxy/api/routes_monitoring.go
cmd/relayproxy/api/server.go
cmd/relayproxy/api/server_test.go
cmd/relayproxy/config/config.go
cmd/relayproxy/config/config_test.go
website/docs/relay-proxy/configure-relay-proxy.mdx

add a boolean EnableVersionHeader in configuration to conditionnally register the VersionHeader custom middleware and disable the header x-gofeatureflag-version
issue: https://github.com/thomaspoignant/go-feature-flag/issues/3140
Add a new boolean named `EnableVersionHeader` in documentation with default value set to `true` in order to not change initial behavior.
The idea behind this is to allow end user to disable `VersionHeader` custom middleware to remove `x-gofeatureflag-version` header.
Resolve #3140

feat(relayproxy): allow disable VersionHeader middleware

---

exporter/s3exporterv2/exporter.go
exporter/s3exporterv2/exporter_test.go
retriever/s3retrieverv2/retriever.go
retriever/s3retrieverv2/retriever_test.go
testutils/s3managerv2_mock.go

As mentioned in #3142, there is some issue when initialiasing the aws-sdk with a `nil` context.
In this PR we ensure that we always have a `context.Context` set when calling the s3 retriever but also the s3 exporter.
Resolve #3142

fix(s3): Use a default context if not provided in retriever and exporter

---

.goreleaser.yaml

Address goreleaser configuration change https://goreleaser.com/deprecations/#archivesbuilds.

fix(goreleaser): address deprecation builds

---

Makefile

`golanglint-ci` v2 is out and needs to rework the configuration file.
Since CI is taking latest it blocks all the pipelines, this PR is to ensure we can still release things while waiting to migrate to v2 #3244.

ci: fixed version for golangci-lint to 1.64.6

---

exporter/even_store_test.go
feature_flag.go
variation.go

- What was the problem? It was getting too much time to flush/send events from exporter and doing it synchronously doesn't make a lot of sense, while heavily increasing response times.
- How it is resolved?
Whole events exporter now runs in different goroutine
- How can we test the change?
- If there are breaking changes, please describe them in detail and why we cannot avoid them.
Tested with 1000rps, traced for 1 minute 
Before
After
This duration was saved during the trace (60seconds)
full pprof traces: 
https://drive.google.com/file/d/1ZpxxOnk1CQ3bXRMYUCowwXgrebO3HAcF/view?usp=sharing
https://drive.google.com/file/d/1KyFWdtl6LXDV03EKkaLIs5ipV3Aar7nP/view?usp=sharing
Resolve #

perf: Separate goroutine for exporter flow

---

cmd/relayproxy/config/config.go
cmd/relayproxy/config/config_test.go
cmd/relayproxy/testdata/config/valid-env-exporters-kafka.yaml

Allow to configure Kafka Addresses through environment variables.
Resolve #3280

fix(relayproxy): configure kafka addresses with env variables

---

cmd/relayproxy/api/routes_monitoring.go
cmd/relayproxy/api/routes_monitoring_test.go
cmd/relayproxy/config/config.go
cmd/relayproxy/config/config_test.go
cmd/relayproxy/helm-charts/relay-proxy/values.yaml
cmd/relayproxy/testdata/config/validate-array-env-file-envprefix.yaml
website/docs/relay-proxy/configure-relay-proxy.mdx

Following PR #3336, this solution allow to add a prefix for env variables.
It also remove the `debug` option that was deprecated
Resolve #3336

feat(relay-proxy): allow to set a prefix for env variables

---

cmd/relayproxy/service/gofeatureflag.go

When in the **relayproxy** you are configuring the `config` field for a kafka exporter, you had the error `error while exporting data: writer: producer: kafka: client has run out of available brokers to talk to`.
See #3307 to have a failing configuration.
This PR fix the issue, by creating a new struct instead of changing the reference.
Resolve #3307

fix(relayproxy): Error while configuring kafka exporter config

---

go.mod

Version `1.24.3` has a CVE on stdlib, bumping to latest version.

chore: Bump go version

---

openfeature/providers/python-provider/pyproject.toml

Depending on the python provider brings in the deprecated `asyncio` package (which has been part of base python for a long time)
Resolve #3606

chore: Remove dependency on asyncio since it's part of base python

---

.gemini/config.yaml

We configure Gemini Code Assyst to be triggered only manually.

chore: Configuration of Gemini Code Assyst

---

README.md

There was an error in the video for one of the rules.
Resolve #3714

docs: Change home video because typo in rule

---

.github/workflows/ci-helm.yaml
.github/workflows/doc-test.yml
cmd/relayproxy/helm-charts/relay-proxy/README.md
cmd/relayproxy/helm-charts/relay-proxy/README.md.gotmpl
cmd/relayproxy/helm-charts/relay-proxy/templates/_helpers.tpl
cmd/relayproxy/helm-charts/relay-proxy/templates/deployment.yaml
cmd/relayproxy/helm-charts/relay-proxy/templates/service.yaml
cmd/relayproxy/helm-charts/relay-proxy/templates/tests/test-monitoring-port.yaml
cmd/relayproxy/helm-charts/relay-proxy/templates/tests/test-service-ports.yaml
cmd/relayproxy/helm-charts/relay-proxy/values.yaml

**What was the problem?**
The relay-proxy Helm chart lacked support for separating monitoring traffic from application traffic. Users needed the ability to expose a dedicated monitoring port for health checks and monitoring while keeping the main HTTP port for application traffic.
**How it is resolved?**
- Added `monitoringPort` configuration support in the relay-proxy Helm chart
- When `monitoringPort` is specified in `relayproxy.config`, the chart automatically:
- Exposes the monitoring port alongside the HTTP port
- Uses the monitoring port for liveness and readiness probes
- Routes health check requests (`/health` endpoint) to the monitoring port
- Maintains full backward compatibility for existing deployments
**How can we test the change?**
1. **With monitoringPort**: Deploy with …

feat(helm): Add monitoringPort support for relay-proxy Helm chart

---

cmd/cli/evaluate/evaluate.go

Hey :)
I've noticed inconsistency in naming of one local variable and decided to rename it.

style: rename local variable for the sake of camelCase
