thomaspoignant/go-feature-flag

README.md
Change the link to the documentation to use new version of godoc.
=> Change link to doc

go.sum, internal/flags/flag.go, internal/flags/flag_test.go
This PR simplifies how we affect users to the right cohort.
This does not change how you interact with the library, but it changes a bit the affectation, so not the same users will be affected by this new version.
Since the module has only 1 day, this breaking change should not impact a lot of people.
=> Change the way to affect people in the cohort

.github/auto_assign-issues.yml, .github/auto_assign.yml
=> Add assignee to issue and PR

README.md
Update documentation to explain how to create a User.
Resolve #35
=> Add documentation on Users

.github/workflows/codeql-analysis.yml
Add codeql for security checks.
=> Add codeql checks in the repository

config.go
=> Fix typo in comments

internal/flags/flag.go
Rename and un-export UserToJSON.
This is code optimization.
Resolve #44
=> Rename and un-export UserToJSON

.sonarcloud.properties, README.md, examples/file/flags.yaml, examples/file/main.go, examples/github/flags.yaml, examples/github/main.go, examples/http/flags.yaml, examples/http/main.go
Adding examples to have a more complete way to understand how `go-feature-flag` is working.
Resolve #19
=> Add examples

Makefile
`make test` does not work locally, this PR fixes this problem.
=> Fix local make test

README.md
Edit readme to better fit with the new summary feature of the readmes in GitHub
Now we have the titles for all the sections
=> Better summary in the readme

feature_flag.go, ffexporter/log.go, ffexporter/log_test.go, internal/exporter/data_exporter.go, internal/fflog/log.go, internal/notifier/notifier_log.go, internal/notifier/notifier_log_test.go, internal/notifier/notifier_slack.go, internal/notifier/notifier_slack_test.go, internal/notifier/notifier_webhook.go, internal/notifier/notifier_webhook_test.go, variation_test.go
Prefix every log with the date.
=> Refactor fflog to always add the date

README.md
=> Add what is go-feature-flag section

README.md, internal/model/flag.go, internal/model/flag_priv_test.go, internal/model/flag_pub_test.go, internal/model/rollout.go, internal/model/rollout_test.go, internal/notifier/notifier_slack_test.go, testutils/testconvert/convert_types.go, variation_test.go
New rollout capability that allows to progressively increase the percentage of your flag.
This functionality allows you to see how you're feature is performing before rolling out to all users.
Resolve #101
=> Progressive rollout

internal/notifier/notifier_slack_test.go, internal/signer/signer_test.go
=> put test file in test package

internal/model/rollout.go
=> Scheduled add comment

README.md, docs/quickstart.md
Fix broken link in `README.md` and in official documentation
https://github.com/thomaspoignant/go-feature-flag/issues/141
=> fix: broken link

examples/github/main.go
Error in the example, branch is deleted
=> Fix example branch

internal/exporter/data_exporter_test.go, internal/exporter/feature_event.go, variation.go
=> Remove unused param flag

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/change.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature.md
=> Github Issue update templates

docs/index.md, mkdocs.yml
There is a broken link in the doc + the sitemap is not correctly generating.
=> (doc) fix sitemap + broken link

.github/workflows/bench.yaml, Makefile, feature_flag_bench_test.go, testdata/benchmark/flag-config.yaml, variation.go
Add some benchmark using `go test -bench`.
This bench will be run at each merge to `main` and we will be able to have dashboards available at https://thomaspoignant.github.io/go-feature-flag/dev/bench/index.html
Resolve #155
=> Benchmarking

docs/data_collection/custom.md, docs/data_collection/index.md, docs/flag_file/custom.md, docs/flag_file/index.md, mkdocs.yml, retriever.go
A documentation on how to extend `retriever` and `exporter`.
Resolve #151
=> (doc) How to extend go-feature-flag

README.md, docs/configuration.md, docs/flag_format.md, docs/index.md, docs/quickstart.md
Correcting some grammar errors and sentences in README to improve readability.
=> (doc) correcting minor grammar errors and sentences in README.md

README.md, docs/index.md
Fossa is not working well and I don't want to use it anymore.
=> Remove fossa

.gitignore
Update `.gitignore` with `venv`.
=> Add venv in gitignore

docs/data_collection/file.md
Add optional fields to the documentation.
=> Set optional fields

examples/retriever_configmap/main.go
Fix comment in k8s confingmap example
=> Fix comment in k8s confingmap example

internal/flag/resolution_detail.go
enforce type `errorCode` in `resolutionDetails`
=> enforce type errorCode

.github/workflows/release.yml, .gitignore, .goreleaser.yaml, Makefile, cmd/migrationcli/DOCKERHUB.md, cmd/migrationcli/Dockerfile
Setup `goreleaser` for the migration command line.
=> Setup goreleaser for migrationcli

.github/workflows/release.yml, .goreleaser.yaml
=> Fix goreleaser

cmd/migrationcli/DOCKERHUB.md, cmd/migrationcli/README.md
Add readme for the migration cli
=> Add readme for the migration cli

docs/src/theme/Footer/styles.module.css
Avoid horizontal scroll on mobile
Resolve #387
=> Avoid horizontal scroll on mobile

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
Add google analytics tracking to the docusaurus website.
Resolve #389
=> add analytics

README.md
=> Broken link in the new readme

cmd/migrationcli/main.go, docs/docs/migrate_v0_v1.md
Add documentation for the migration
Resolve #370
=> Migration cli doc

docs/docusaurus.config.js, docs/src/components/features/index.js, docs/src/components/features/styles.module.css
Add new section for SDKs in the home page
=> Add new section for SDKs in the home page

.github/workflows/doc-test.yml, Makefile, docs/package-lock.json, docs/src/components/editor/Variation/index.js
Add makefile command to build doc
=> Add makefile command to build doc + fix doc build

website/src/components/home/HomeHeader/styles.module.css
put SVG in background
Resolve #
=> Top bar on top of SVG

README.md
=> Fix readme merge issue

.github/workflows/release.yml, .kodiak.toml
=> fix merge doc to main

README.md, examples/demo/README.md
=> Change video for demo

CONTRIBUTING.md
Add contributing guidelines for documentation
=> Add contributing guidelines for documentation

README.md
=> Remove rule name

website/docs/getting_started/using-openfeature.md, website/versioned_docs/version-v1.0.0-rc.5/getting_started/using-openfeature.md
=> Change link to image

.github/workflows/doc-preview.yaml
=> Deploy netlify

website/docs/openfeature_sdk/openfeature_dotnet.mdx, website/docs/openfeature_sdk/openfeature_go.mdx, website/docs/openfeature_sdk/openfeature_java.mdx, website/docs/openfeature_sdk/openfeature_javascript.mdx
Documentation: Add link to source of the providers
=> Add link to sources

internal/flag/internal_flag.go, website/docs/openfeature_sdk/openfeature_dotnet.mdx
The doc is outdated and the nuget link are wrong.
=> Fix doc for nuget link

website/docusaurus.config.js
Support more language coloration
=> Documentation: Support more language coloration

website/package-lock.json, website/package.json
Update dependencies for docusaurus
=> doc: Update dependencies for docusaurus

Makefile
increase lint timeout To 5 minutes
=> increase lint timeout

website/docusaurus.config.js, website/package-lock.json, website/package.json
Add search in website using https://github.com/easyops-cn/docusaurus-search-local
Resolve #487
=> Add search in website

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/doc-test.yml
Change scope or PR in GHA to be sure that CI is launch when coming from another GHA
=> Be sure that CI is launch when coming from another GHA

.github/workflows/ci.yml
Migrate form coverall to codecov.
=> Migrate form coverall to codecov

README.md
=> Change badge for coverage

.github/workflows/ci.yml
=> Parallelize more the CI

cmd/relayproxy/controller/utils_test.go
Add test for utils in relay proxy
=> Add test for utils in relay proxy

website/docs/linter.md
Add documentation for the linter
=> Add doc for linter

.goreleaser.yaml, README.md, cmd/lint/DOCKERHUB.md, cmd/lint/README.md
Change name of build from go-feature-flag-lint-cli to go-feature-flag-lint
=> Change name of build from go-feature-flag-lint-cli to go-feature-flag-lint

website/docusaurus.config.js
=> [skip ci] Change swagger URL

internal/flag/internal_flag.go, variation_test.go
Fix issues with introduction of Cacheable
=> Fix issues with introduction of Cacheable

website/docusaurus.config.js, website/src/pages/editor/index.js
Small fixes on the website
- Change title of the editor
- Fix link to edit pages
=> Small fixes on the website

codecov.yml
=> Codecov ignoring some folder

.goreleaser.yaml, Makefile
Put CGO_ENABLED=0 for each builds
=> Put CGO_ENABLED=0 for each builds

.github/workflows/ci-helm.yaml
CI was not detecting file changes in helm lint workflow
=> Fix: CI was not detecting file changes in helm lint workflow

.github/workflows/doc-test.yml
Avoid building doc if no change
=> CI: Avoid building doc if no change

.github/workflows/ci-helm.yaml
=> CI: Rename helm lint workflow

website/docs/migrate_v0_v1.md, website/versioned_docs/version-v1.0.0-rc.5/migrate_v0_v1.md, website/versioned_docs/version-v1.0.0/migrate_v0_v1.md, website/versioned_docs/version-v1.0.1/migrate_v0_v1.md, website/versioned_docs/version-v1.1.0/migrate_v0_v1.md, website/versioned_docs/version-v1.2.0/migrate_v0_v1.md, website/versioned_docs/version-v1.2.1/migrate_v0_v1.md, website/versioned_docs/version-v1.2.2/migrate_v0_v1.md, website/versioned_docs/version-v1.3.0/migrate_v0_v1.md, website/versioned_docs/version-v1.4.0/migrate_v0_v1.md, website/versioned_docs/version-v1.5.0/migrate_v0_v1.md, website/versioned_docs/version-v1.5.1/migrate_v0_v1.md, website/versioned_docs/version-v1.6.0/migrate_v0_v1.md
fix documentation migration-cli
=> fix documentation migration-cli

.github/dependabot.yml
Dependabot configuration for docusaurus
=> Dependabot configuration for docusaurus

website/src/components/editor/Variation/index.js
[test](https://user-images.githubusercontent.com/35093673/227847956-f16eeeb7-d9aa-4d6f-bf85-63df418469a5.webm)
Resolve #612
=> (bug) editor: Removing a variation remove all of them

examples/demo/demo-flags.yaml, examples/demo/main.go
Missing flag file for the demo app.
Resolve #634
=> Add flags for demo

website/docusaurus.config.js, website/src/css/custom.css
=> Add icons in the menu

.pre-commit-config.yaml, cmd/relayproxy/api/server.go, cmd/relayproxy/config/config.go, cmd/relayproxy/config/config_test.go
Use a set to store apiKeys so we can test it faster
=> Use a set to store apiKeys so we can test it faster

website/src/pages/specification/provider-cache.md
add a specifications page for the provider cache
=> add a specifications page for the provider cache

.github/workflows/release.yml, website/docs/relay_proxy/deploy_relay_proxy.md
Add helm-docs generation in the release process.
=> Add helm-docs generation in the release process.

cmd/migrationcli/main_test.go
=> migration cli: Adding test for main

website/docusaurus.config.js, website/src/pages/index.js
=> Change website description

.goreleaser.yaml
=> [skip ci] fix docker release tag

cmd/relayproxy/helm-charts/relay-proxy/README.md
Automated pull request to update relay-proxy helm chart README
=> Update relay proxy helm README

.github/dependabot.yml
Dependabot can update github actions
=> Dependabot can update github actions

.github/workflows/lint-flag-files.yml, examples/.gitignore, examples/retriever_multiple_config_files/flags.yaml, examples/retriever_multiple_config_files/flags2.yaml
Add linting of all example flags
=> Add linting of all example flags

.github/workflows/release.yml, .goreleaser.yaml, cmd/relayproxy/README.md, website/docs/linter.mdx, website/docs/migrate_v0_v1.md, website/docs/relay_proxy/install_relay_proxy.md
=> Fix scoops issue + use the org repo

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.10.2
=> Bump relay-proxy helm chart version v1.10.2

website/src/components/doc/cards/styles.module.css
=> Fix blue color on buttons

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.10.4
=> Bump relay-proxy helm chart version v1.10.4

.github/workflows/check_openfeature_pr.yaml, .github/workflows/check_openfeature_pr.yml, .gitignore, openfeature/ci_scripts/check_prs_and_open_issue.js, openfeature/ci_scripts/package-lock.json, openfeature/ci_scripts/package.json
Sometimes it is hard to follow which pull requests needs to be checked in the Open Feature contrib repositories.
This cron will call a script that checks each open PR on the contrib repos and look if it is linked to GO Feature Flag.
If there are PRs we open an issue to be sure that we will work on it.
=> Adding a cron to open issue with open feature PR waiting to be checked

website/package-lock.json, website/package.json
=> Bump docusaurus

website/src/components/editor/FlagDisplay/index.js
https://sonarcloud.io/project/issues?open=AYjKcos05aesmyw3GGUk&id=thomaspoignant_go-feature-flag
=> Fix sonar issue in editor for metadata

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.12.0
=> Bump relay-proxy helm chart version v1.12.0

cmd/editor/main.go
Editor API: Add endpoint /health
=> editor-api: Add endpoint /health

website/docusaurus.config.js, website/src/components/editor/FlagForm/index.js
Test flag configuration in the editor
Resolve #798
=> Test flag configuration in the editor

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.13.0
=> Bump relay-proxy helm chart version v1.13.0

.github/workflows/ci.yml, .goreleaser.yaml
Fix goreleaser deprecation + add check to CI
Resolve #944
=> Fix goreleaser deprecation + add check to CI

website/versioned_docs/version-v1.13.0/go_module/data_collection/custom.md
Minor spelling issue was found in the docs and resolved.
=> docs: Spelling in data collection custom.md

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.14.0
=> Bump relay-proxy helm chart version v1.14.0

website/docs/configure_flag/export_flags_usage.mdx, website/docs/configure_flag/store_your_flags.mdx, website/docs/openfeature_sdk/client_providers/openfeature_javascript.mdx, website/docs/openfeature_sdk/sdk.mdx, website/docs/openfeature_sdk/server_providers/openfeature_dotnet.mdx, website/docs/openfeature_sdk/server_providers/openfeature_go.mdx, website/docs/openfeature_sdk/server_providers/openfeature_java.mdx, website/docs/openfeature_sdk/server_providers/openfeature_javascript.mdx, website/src/components/doc/cardv2/index.js, website/src/components/doc/cardv2/styles.module.css, website/src/components/doc/configCardContent/index.js, website/src/components/doc/configCardContent/styles.module.css, website/src/components/doc/sdkCardContent/index.js, website/src/components/doc/sdkCardContent/styles.module.css, website/src/css/custom.css
=> Some doc improvements

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.14.1
=> Bump relay-proxy helm chart version v1.14.1

website/docs/relay_proxy/install_relay_proxy.md
Change installation doc to use directly scoop
=> Change installation doc to use directly scoop

openfeature/provider_tests/java-integration-tests/pom.xml, openfeature/provider_tests/java-integration-tests/src/test/java/org/gofeatureflag/integrationtests/ProviderTests.java
Add a shutdown task after tests
=> Add a shutdown task after tests

internal/cache/notification_service_priv_test.go, internal/cache/notification_service_test.go
=> Improving coverage

examples/readme.md
=> Add readme for examples

examples/openfeature_nodejs/README.md, examples/openfeature_nodejs/config.goff.yaml, examples/openfeature_nodejs/docker-compose.yaml, examples/openfeature_nodejs/nodejs-app/.dockerignore, examples/openfeature_nodejs/nodejs-app/Dockerfile, examples/openfeature_nodejs/nodejs-app/index.ts, examples/openfeature_nodejs/nodejs-app/package-lock.json, examples/openfeature_nodejs/nodejs-app/package.json, examples/openfeature_nodejs/nodejs-app/tsconfig.json, examples/readme.md
=> Example Node.js Application

examples/openfeature_nodejs/nodejs-app/index.ts
stop reinstanciate Openfeature at every evaluation
=> fix: stop reinstanciate Openfeature at every evaluation

openfeature/provider_tests/integration_tests.sh
=> Activate integration tests

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.15.0
=> Bump relay-proxy helm chart version v1.15.0

website/src/components/home/HomeHeader/index.js, website/src/components/home/HomeHeader/styles.module.css
=> Add get started button

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.15.1
=> Bump relay-proxy helm chart version v1.15.1

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml, cmd/relayproxy/helm-charts/relay-proxy/values.yaml
Automated pull request to bump relay-proxy helm chart version v1.15.2
=> Bump relay-proxy helm chart version v1.15.2

.pre-commit-config.yaml, feature_flag.go
=> fix: use the wrong logger

cmd/relayproxy/main.go, cmd/relayproxy/metric/metrics.go, cmd/relayproxy/metric/metrics_test.go, cmd/relayproxy/metric/notifier_prometheus.go, cmd/relayproxy/metric/notifier_prometheus_test.go, cmd/relayproxy/service/gofeatureflag.go, cmd/relayproxy/service/notifier_prometheus.go, cmd/relayproxy/service/notifier_websocket.go, cmd/relayproxy/service/notifier_websocket_test.go
Add new metrics to follow flag changes in the server
Resolve #665
=> Add new prometheus metrics to follow flag changes in the server

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.17.0
=> Bump relay-proxy helm chart version v1.17.0

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.18.0
=> Bump relay-proxy helm chart version v1.18.0

website/docs/openfeature_sdk/client_providers/openfeature_android.mdx, website/docs/openfeature_sdk/sdk.mdx, website/docs/openfeature_sdk/server_providers/openfeature_java.mdx, website/src/components/home/features/index.js
Add Kotlin to the list of the supported languages
=> Add Kotlin to the list of the supported languages

.pre-commit-config.yaml
=> Add black pre-commit

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.18.2
=> Bump relay-proxy helm chart version v1.18.2

cmd/relayproxy/testdata/config/invalid-yaml.yaml, cmd/relayproxy/testdata/config/valid-file.json, cmd/relayproxy/testdata/config/valid-file.toml, cmd/relayproxy/testdata/config/valid-file.yaml, cmd/relayproxy/testdata/config/valid-yaml-notifier.yaml
Fix Links in configuration files
=> Fix Links in configuration files

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.19.0
=> Bump relay-proxy helm chart version v1.19.0

.github/dependabot.yml, openfeature/providers/python-provider/README.md
Dependabot update for providers
=> Dependabot update for providers

website/src/components/home/HomeHeader/styles.module.css, website/src/components/home/features/index.js, website/src/components/home/using-it/index.js, website/src/components/home/using-it/styles.module.css
=> website: Fixing some responsive things

website/docs/getting_started/using-openfeature.md
docs: Update Open Feature package being used in the getting started session
Resolve #
=> docs: update open feature refs to newer package

README.md, cmd/relayproxy/DOCKERHUB.md, cmd/relayproxy/DOCKERHUB_deprecated.md, cmd/relayproxy/README.md, website/docusaurus.config.js, website/src/pages/slack/index.mdx, website/src/pages/slack/styles.module.css, website/versioned_docs/version-v0.22.3/index.md, website/versioned_docs/version-v0.23.0/index.md, website/versioned_docs/version-v0.24.0/index.md, website/versioned_docs/version-v0.25.2/index.md, website/versioned_docs/version-v0.26.1/index.md, website/versioned_docs/version-v0.27.2/index.md, website/versioned_docs/version-v0.28.1/index.md, website/versioned_docs/version-v0.28.2/index.md
Adding a new link to join Slack
=> Adding a new link to join slack

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.20.1
=> Bump relay-proxy helm chart version v1.20.1

website/docusaurus.config.js
=> [skip ci] change DNS for test API

.schema/flag-schema.json, cmd/jsonschema-generator/main.go
=> fix issue in json schema

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.20.2
=> Bump relay-proxy helm chart version v1.20.2

cmd/relayproxy/helm-charts/relay-proxy/templates/hpa.yaml
Changed minumum api version to `v2beta2` and definition to match updated specs. Original `v2beta1` is incompatible with `v2beta2` and `v2`.
Resolve #
=> [BUGFIX] v2beta1 api spec is incompatible with v2, adjusted to v2beta2

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.21.0
=> Bump relay-proxy helm chart version v1.21.0

package_info.go
=> Fix example in godoc

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.22.0
=> Bump relay-proxy helm chart version v1.22.0

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.23.0
=> Bump relay-proxy helm chart version v1.23.0

cmd/relayproxy/api/server.go, cmd/relayproxy/controller/ws_flag_change.go
Fixing some minor linting issues
=> Fixing some minor linting issues

openfeature/providers/python-provider/gofeatureflag_python_provider/data_collector_hook.py, openfeature/providers/python-provider/gofeatureflag_python_provider/provider.py
This PR fixes the issue from the issue #1573.
It solves the problem of `metaclass`.
Resolve #1573
=> Python provider: Fix issue with metaclass

.github/workflows/release-python-provider.yml
CI, use `colathro/toml-editor` instead of `ciiiii/toml-editor`
=> [skip ci] Move to colathro/toml-editor

openfeature/providers/python-provider/README.md
=> Fix format of the Python example of OpenFeature in README

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.24.1
=> Bump relay-proxy helm chart version v1.24.1

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.24.2
=> Bump relay-proxy helm chart version v1.24.2

ADOPTERS.md, README.md
Why: It builds the trust on project
How: By adding ADOPTERS.md file and updated README
Tags: [adopters]
=> Added adopters to the project

.github/workflows/release.yml
Fix release speed CI during release
=> Fix release speed CI during release

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.25.1
=> Bump relay-proxy helm chart version v1.25.1

openfeature/provider_tests/dotnet-integration-tests/ProviderTests/ProviderTests.cs
Fix .NET deprecation SetProvider
=> [dotnet integration tests] Fix deprecation SetProvider

cmd/relayproxy/api/server.go, cmd/relayproxy/docs/docs.go, cmd/relayproxy/docs/swagger.json, cmd/relayproxy/docs/swagger.yaml, cmd/relayproxy/model/ofrep_configuration.go, cmd/relayproxy/ofrep/configuration.go, cmd/relayproxy/ofrep/configuration_test.go, cmd/relayproxy/ofrep/evaluate.go, cmd/relayproxy/ofrep/evaluate_test.go, feature_flag.go, feature_flag_test.go
Adding OFREP Configuration Endpoint from https://github.com/open-feature/protocol/pull/9
=> feat: Adding OFREP Configuration Endpoint

cmd/relayproxy/docs/docs.go, cmd/relayproxy/docs/swagger.json, cmd/relayproxy/docs/swagger.yaml, cmd/relayproxy/ofrep/configuration.go
OFREP swagger Remove error 400
=> OFREP swagger Remove error 400

codecov.yml, go.mod
=> Bump GO toolchain

exporter/fileexporter/exporter_test.go, exporter/gcstorageexporter/exporter_test.go, exporter/kafkaexporter/exporter_test.go, exporter/logsexporter/exporter_test.go, exporter/s3exporter/exporter_test.go, exporter/s3exporterv2/exporter_test.go, exporter/sqsexporter/exporter_test.go, exporter/webhookexporter/exporter_test.go
Minor change - A few of the test messages didn't align with the values.
- [+] Bugfix (non-breaking change that solves an issue)
Resolve #
- [+] I have tested this code
- [+] I have added unit test to cover this code
- [N/A ] I have updated the documentation (`README.md` and `/website/docs`)
- [ N/A] I have followed the [contributing guide](CONTRIBUTING.md)
=> Fix test messages for IsBulk

.github/workflows/pr-lint.yaml
=> Add PR lint for PR title

.github/dependabot.yml, .github/workflows/pr-lint.yaml
=> feat: Add prefix dependabot

codecov.yml, internal/internalerror/targeting_not_apply_test.go
=> chore: increase coverage

.github/dependabot.yml, website/package-lock.json, website/package.json
=> fix: revert website update

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.27.0
=> ci(helm): Bump relay-proxy helm chart version v1.27.0

cmd/migrationcli/main.go
Change the write file level for the migration cli.
=> fix(migration-cli): Change write file level

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.28.2
=> chore(helm): Bump relay-proxy helm chart version v1.28.2

website/docusaurus.config.js
=> doc: change footer links

.pre-commit-config.yaml
Bump `golangci-lint` version for `pre-commit`
=> chore(pre-commit): Bump golangci-lint version

.goreleaser.yaml, cmd/relayproxy/DockerfileGoreleaserBookworm
Release bookworm docker images
=> feat: Release bookworm docker images

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.29.0
=> chore(helm): Bump relay-proxy helm chart version v1.29.0

website/docs/openfeature_sdk/server_providers/openfeature_java.mdx, website/versioned_docs/version-v1.29.0/openfeature_sdk/server_providers/openfeature_java.mdx
=> fix: Update openfeature artifact ID

cmd/relayproxy/helm-charts/relay-proxy/README.md
Automated pull request to update relay-proxy helm chart README
=> docs(helm): Update relay proxy helm README

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.30.0
=> chore(helm): Bump relay-proxy helm chart version v1.30.0

website/.ci/sdkVersions.go, website/docs/openfeature_sdk/client_providers/openfeature_android.mdx, website/docs/openfeature_sdk/client_providers/openfeature_javascript.mdx, website/docs/openfeature_sdk/sdk.mdx, website/docs/openfeature_sdk/server_providers/openfeature_dotnet.mdx, website/docs/openfeature_sdk/server_providers/openfeature_go.mdx, website/docs/openfeature_sdk/server_providers/openfeature_java.mdx, website/docs/openfeature_sdk/server_providers/openfeature_javascript.mdx, website/docs/openfeature_sdk/server_providers/openfeature_python.md, website/sdk-versions.json, website/src/components/doc/sdkCardContent/index.js
Adding badges to provider pages
=> docs(providers): Adding badges to provider pages

.goreleaser.yaml
=> chore(goreleaser): Specify goreleaser version

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.31.0
=> chore(helm): Bump relay-proxy helm chart version v1.31.0

feature_flag.go, feature_flag_test.go, internal/flag/internal_flag.go, testdata/invalid-flag-config.json, testdata/invalid-flag-config.yaml
Report original error when retriever failed
Resolve #2090
=> fix(relay-proxy): Report original error when retriever failed

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.31.1
=> chore(helm): Bump relay-proxy helm chart version v1.31.1

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.31.2
=> chore(helm): Bump relay-proxy helm chart version v1.31.2

.github/workflows/sponsors.yaml, README.md
Display sponsors in the README
=> feat: Display sponsors in the README

.github/workflows/sponsors.yaml, README.md
Automated pull request to update readme with the sponsors list
=> docs(README): Update sponsors list

cmd/editor/lamda_adapter.go, cmd/editor/main.go
allow to run the API as AWS lambda
#2142
=> feat(editor-api): allow to run the API as AWS lambda

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.32.0
=> chore(helm): Bump relay-proxy helm chart version v1.32.0

cmd/relayproxy/DOCKERHUB.md, cmd/relayproxy/DOCKERHUB_deprecated.md, cmd/relayproxy/DOCKERHUB_thomaspoignant.md, cmd/relayproxy/testdata/dockerhub-example/.gitignore, cmd/relayproxy/testdata/dockerhub-example/flags.goff.yaml, cmd/relayproxy/testdata/dockerhub-example/goff-proxy.yaml, website/docs/experimental/ofrep.md, website/versioned_docs/version-v1.24.0/experimental/ofrep.md, website/versioned_docs/version-v1.24.1/experimental/ofrep.md, website/versioned_docs/version-v1.24.2/experimental/ofrep.md, website/versioned_docs/version-v1.25.0/experimental/ofrep.md, website/versioned_docs/version-v1.25.1/experimental/ofrep.md, website/versioned_docs/version-v1.26.0/experimental/ofrep.md, website/versioned_docs/version-v1.27.0/experimental/ofrep.md, website/versioned_docs/version-v1.28.0/experimental/ofrep.md, website/versioned_docs/version-v1.28.1/experimental/ofrep.md, website/versioned_docs/version-v1.28.2/experimental/ofrep.md, website/versioned_docs/version-v1.29.0/experimental/ofrep.md, website/versioned_docs/version-v1.30.0/experimental/ofrep.md, website/versioned_docs/version-v1.31.0/experimental/ofrep.md, website/versioned_docs/version-v1.31.1/experimental/ofrep.md, website/versioned_docs/version-v1.31.2/experimental/ofrep.md, website/versioned_docs/version-v1.32.0/experimental/ofrep.md
- Fix configuration for docker examples
Resolve #2172
=> docs(example): Fix configuration for docker examples

website/blog/2024-08-02-feature-flagging-in-the-SDLC/index.md
Add article Feature Flagging in the SDLC
=> docs(blog): Add article Feature Flagging in the SDLC

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.33.0
=> chore(helm): Bump relay-proxy helm chart version v1.33.0

README.md
Automated pull request to update readme with the sponsor list
=> docs(README): Update sponsor list

README.md
Update readme with OpenFeature example
Resolve #2141
=> feat: Update readme with OpenFeature example

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.34.0
=> chore(helm): Bump relay-proxy helm chart version v1.34.0

.schema/flag-schema.json
Automated pull request to release a new version of the jsonschema v1.34.0
=> feat(jsonschema): Release a new version of the jsonschema v1.34.0

ADOPTERS.md
=> feat: Adding alternative as adopter

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.34.1
=> chore(helm): Bump relay-proxy helm chart version v1.34.1

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.34.2
=> chore(helm): Bump relay-proxy helm chart version v1.34.2

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.34.3
=> chore(helm): Bump relay-proxy helm chart version v1.34.3

cmd/editor/main.go, cmd/lint/linter.go, cmd/migrationcli/converter/converter.go, internal/cache/in_memory_cache.go, model/dto/converter_test.go, model/dto/dto.go
add deprecation logger for v0 flags
Resolve #2399
=> feat: add deprecation log for v0 flags

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.35.0
=> chore(helm): Bump relay-proxy helm chart version v1.35.0

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.36.0
=> chore(helm): Bump relay-proxy helm chart version v1.36.0

website/docs/openfeature_sdk/server_providers/openfeature_go.mdx, website/versioned_docs/version-v1.36.0/openfeature_sdk/server_providers/openfeature_go.mdx
=> docs(GO provider): Add section for unit testing

go.mod
=> chore: bump to go 1.22.8

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.36.1
=> chore(helm): Bump relay-proxy helm chart version v1.36.1

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.37.0
=> chore(helm): Bump relay-proxy helm chart version v1.37.0

ADOPTERS.md
This PR includes the Mecena project in the list of adopters.
=> Add Mecena to adopters

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.38.0
=> chore(helm): Bump relay-proxy helm chart version v1.38.0

website/docs/go_module/configuration.md
When reading the [docs](https://gofeatureflag.org/docs/go_module/configuration#example), I noticed a bunch of fields and values were not aligned.
Aligns them. Fixes white space.
Tested by viewing in GitHub.
Resolve #
=> docs: fix formatting configuration.md

package-lock.json, website/package-lock.json, website/package.json
=> chore: Bump docusaurus

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.39.0
=> chore(helm): Bump relay-proxy helm chart version v1.39.0

.github/ci-scripts/free_space.sh, .github/workflows/release.yml
=> Test Free space

.github/workflows/doc-deploy.yml
force orphan for gh-pages branch
=> ci(docs): force orphan for gh-pages branch

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.39.1
=> chore(helm): Bump relay-proxy helm chart version v1.39.1

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.40.0
=> chore(helm): Bump relay-proxy helm chart version v1.40.0

go.mod
=> chore(go): Bump GO to version v1.23.0

.github/workflows/ci.yml
fix ICU error in integration tests for dotnet
=> ci(icu): fix ICU error in integration tests for dotnet

website/docs/contributing/_category_.json, website/docs/contributing/index.md, website/docs/go_module/_category_.json, website/docusaurus.config.js
=> docs: Adding contributing page to the doc

.github/workflows/ci.yml
It seems that the version v4 has been deleted, we are rolling back to v3.
=> fix: rollback action poetry

website/versioned_docs/version-v1.41.0/tooling/cli.mdx, website/versioned_docs/version-v1.41.0/tooling/migrate_v0_v1.md
Create a pull request to update docker tooling README
=> docs(tooling): Update docker tooling README

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.41.1
=> chore(helm): Bump relay-proxy helm chart version v1.41.1

ADOPTERS.md
Add Grafana Labs as a happy GO Feature Flag adopter!
=> feat: Add Grafana Labs as adopter

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.41.2
=> chore(helm): Bump relay-proxy helm chart version v1.41.2

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.41.3
=> chore(helm): Bump relay-proxy helm chart version v1.41.3

website/docusaurus.config.js, website/package-lock.json, website/package.json
Add google tag manager support
=> feat: Add google tag manager support

.github/workflows/ci-helm.yaml, .github/workflows/ci.yml, .github/workflows/doc-test.yml, .github/workflows/release-helm.yml
Following the report on #3208, we are replacing `tj-actions` by a non compromised GitHub Action.
All the secrets have been rotated so we should not have any issue on this repository anymore.
Resolve #3208
=> fix(security): Fix security issue when using tj-actions as GitHub Action

website/data/sdk.js, website/docs/sdk/client_providers/openfeature_angular.mdx, website/docs/sdk/server_providers/openfeature_nestjs.mdx
=> docs: Add nestJS and Angular doc

feature_flag.go, variation.go, variation_test.go
Refactor ffclient.New to be readable
=> fix: Refactor ffclient.New to be readable

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.43.0
=> chore(helm): Bump relay-proxy helm chart version v1.43.0

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.43.1
=> chore(helm): Bump relay-proxy helm chart version v1.43.1

exporter/fileexporter/exporter.go
=> fix(lint): Not writting the correct error in the error message

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.44.0
=> chore(helm): Bump relay-proxy helm chart version v1.44.0

website/docs/integrations/export-evaluation-data/aws-s3.mdx, website/docs/integrations/store-flags-configuration/aws-s3.mdx
Adding documentation about s3 compatible systems
close #3366
=> docs: Adding documentation about s3 compatible systems

variation.go
Error checking if tracking exporter available
=> fix(tracking): Error checking if tracking exporter available

go.mod
=> chore(go): Bump GO version to 1.24.2

website/src/pages/pricing/pricing.jsx
=> docs(pricing): Adding book a demo link

cmd/cli/Dockerfile, cmd/lint/Dockerfile, cmd/relayproxy/DockerfileGoreleaser, cmd/relayproxy/DockerfileGoreleaserRelayProxy
Use static distroless image for more security.
=> feat: Use static distroless image

cmd/cli/evaluate/evaluate_test.go, exporter/even_store_test.go, exporter/feature_event_test.go, exporter/tracking_event_test.go, feature_flag.go, feature_flag_test.go, internal/cache/cache_manager.go, internal/cache/cache_manager_test.go, notifier/microsoftteamsnotifier/notifier_test.go, retriever/azblobstorageretriever/retriever_test.go, retriever/background_updater.go, retriever/background_updater_test.go, retriever/bitbucketretriever/retriever_test.go, retriever/callback/retriver.go, retriever/fileretriever/retriever_test.go, retriever/gcstorageretriever/retriever_test.go, retriever/githubretriever/retriever_test.go, retriever/gitlabretriever/retriever_test.go, retriever/httpretriever/retriever_test.go, retriever/k8sretriever/retriever_test.go, retriever/manager.go, retriever/retriever_test.go, retriever/s3retriever/retriever_test.go, retriever/s3retrieverv2/retriever_test.go, variation.go, variation_all_flags.go, variation_test.go
In this PR I have refactor the retriever manager, to put all the retriever logic in 1 place.
It has a better separation of concerns and should be more maintainable in the future.
=> chore: Refactor retriever manager

website/docusaurus.config.js, website/package-lock.json, website/package.json
=> chore: bump docusaurus dependencies

website/blog/2025-07-01-platformcon-2025-talk/index.md
Add blog post about the platformcon 2025 talk
=> docs(blog): Add blog post about the platformcon 2025

.github/workflows/ci.yml
fix an issue to trigger python test when a change happen.
=> fix(python): CI trigger python test

cmd/relayproxy/api/lambda_handler.go, cmd/relayproxy/api/lambda_handler_test.go, cmd/relayproxy/api/middleware/basepath.go, cmd/relayproxy/api/middleware/basepath_test.go, cmd/relayproxy/api/server.go, cmd/relayproxy/config/config.go, website/docs/contributing/index.md
=> docs: Update community doc

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.45.5
=> chore(helm): Bump relay-proxy helm chart version v1.45.5

website/docs/relay-proxy/configure-relay-proxy.mdx
=> docs: Adding flagset documentation

cmd/relayproxy/controller/ws_flag_change_test.go
Try to fix flacky test around websockets.
=> fix: improve flaky test around websocket

website/src/components/home/features/index.js, website/src/components/home/features/styles.module.css, website/src/pages/index.js
move openfeature up on the main page
=> docs: move openfeature up on the main page

cmd/relayproxy/helm-charts/relay-proxy/Chart.yaml
Automated pull request to bump relay-proxy helm chart version v1.46.0
=> chore(helm): Bump relay-proxy helm chart version v1.46.0

.github/dependabot.yml, openfeature/provider_tests/go-integration-tests/go.mod, website/.ci/go.mod
=> fix: Bumping things to resolve CVE

variation_all_flags_test.go
Fixes flaky tests that were failing intermittently in CI due to timestamp race conditions.
• Fixed race condition in `TestGetFlagStates/Valid_multiple_flags` 
• Fixed same issue in `TestAllFlagsState` tests
• Added robust timestamp handling that maintains comprehensive validation
The tests were using `time.Now().Unix()` to set expected timestamps while the actual implementation was also using `time.Now().Unix()`. These calls could happen microseconds apart, causing Unix timestamps to potentially differ by 1 second when crossing second boundaries - especially under CI load conditions.
- Added `compareJSONWithTimestampHandling()` helper function that:
- Validates timestamps exist and are reasonable (non-zero, recent)
- Normalizes timestamps for structural JSON comparison  
- Maintains …
=> fix: resolve flaky timestamp tests in TestGetFlagStates and TestAllFlagsState

website/docusaurus.config.js, website/package-lock.json, website/package.json
=> docs: Bump docusaurus 3.9.0

website/.ci/go.mod
wrong GO version for the script
=> ci: fix sdk version script
